name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v1

      - name: Check Packer Format
        run: packer fmt -diff -check .

      - name: Validate Packer Template
        run: packer validate csye-6225.pkr.hcl
