name: Build Artifact and Run Packer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      NODE_ENV: test
      CI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U $DB_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run tests
        env:
          DB_NAME: health_check_db
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
          PORT: 8080
          NODE_ENV: test
        run: npm test

      - name: Build application artifact
        run: zip -r webapp.zip . -x "*.git*" "node_modules/*" "*.env" "*.zip"

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup GCP CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

      - name: Build Custom Images with Packer
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS is set to: $GOOGLE_APPLICATION_CREDENTIALS"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS
          packer init .
          packer validate csye-6225.pkr.hcl
          packer build \
            -var "ami_name=${{ secrets.PACKER_AMI_NAME }}" \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "gcp_zone=${{ secrets.GCP_ZONE }}" \
            -var "gcp_destination_project_id=${{ secrets.GCP_DESTINATION_PROJECT_ID }}" \
            csye-6225.pkr.hcl
      - name: Share AMI  Dev and Demo accounts
        run: |
                  AMI_ID=$(aws ec2 describe-images --owners self --filters "Name=name,Values=csye-*" --query 'Images[-1].ImageId' --output text)
                  aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "{\"Add\":[{\"UserId\":\"${{ secrets.AWS_ACCOUNT_ID_DEMO }}\"},{\"UserId\":\"${{ secrets.AWS_ACCOUNT_ID_DEV }}\"}]}"
    
      - name: Share GCP Image with Demo Project
        run: |
                          IMAGE_NAME=$(gcloud compute images list --project=${{ secrets.GCP_PROJECT_ID }} --filter="name~csye-*" --sort-by="~creationTimestamp" --limit=1 --format="value(NAME)")
                          echo "Extracted Image Name: $IMAGE_NAME"
                          if [ -z "$IMAGE_NAME" ]; then
                            echo "Error: No image found!"
                            exit 1
                          fi
                          gcloud compute images add-iam-policy-binding "$IMAGE_NAME" \
                            --project="${{ secrets.GCP_PROJECT_ID }}" \
                            --member="serviceAccount:${{ secrets.GCP_DEMO_ACCOUNT }}" \
                            --role="roles/compute.imageUser"
